// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6qh-lk4fseJCzlxAOhlfnTuF_TBjyKIU',
    appId: '1:285865390735:android:0df8d3247c0a3a167276fa',
    messagingSenderId: '285865390735',
    projectId: 'quizapp-74938',
    storageBucket: 'quizapp-74938.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX3jSGlnJgX_yaM8teeeNW11iDft6bxMg',
    appId: '1:285865390735:ios:0bc7a295bc45cc8b7276fa',
    messagingSenderId: '285865390735',
    projectId: 'quizapp-74938',
    storageBucket: 'quizapp-74938.appspot.com',
    androidClientId: '285865390735-0ll5unf4lb3d06b2r5d1faqi3bs5a9f2.apps.googleusercontent.com',
    iosClientId: '285865390735-2jrlqg9slkrcj7l4qacv4hus5gbbi2rq.apps.googleusercontent.com',
    iosBundleId: 'com.fears.math',
  );
}
